---
- name: Fetch rke2 server token
  ansible.builtin.fetch:
    src: /var/lib/rancher/rke2/server/token
    dest: ./rke2_token
    flat: true
  delegate_to: "{{ rke2_server_address }}"
  register: rke2_token_fetch
  tags:
    - rke2

- name: Set rke2 token as a fact
  ansible.builtin.set_fact:
    rke2_token: "{{ lookup('file', './rke2_token') }}"
  when: rke2_token_fetch
  tags:
    - rke2

- name: Remove the local token file
  ansible.builtin.file:
    path: ./rke2_token
    state: absent
  when: rke2_token_fetch
  tags:
    - rke2

- name: Set up agent config
  ansible.builtin.template:
    src: templates/agent-config.yaml.j2
    dest: /etc/rancher/rke2/config.yaml
  become: true
  tags:
    - rke2

- name: Enable rke2-agent service
  ansible.builtin.service:
    name: rke2-agent
    state: "started"
  become: true
  tags:
    - rke2
