---
- name: Check if /etc/NetworkManager directory exists
  ansible.builtin.stat:
    path: /etc/NetworkManager
  register: networkmanager_stat
  tags:
    - rke2

- name: Create rke2-canal.conf if NetworkManager exists
  ansible.builtin.copy:
    content: |
      [keyfile]
      unmanaged-devices=interface-name:cali*;interface-name:flannel*
    dest: /etc/NetworkManager/conf.d/rke2-canal.conf
  when: networkmanager_stat.stat.exists
  notify:
    - Reload NetworkManager
    - Disable nm-cloud-setup services
  tags:
    - rke2
